# supp/make_sessionInfo.R — regenerate a COMPLETE reproducibility record.
# Loads every analysis package actually used across R/step00..step11 and the
# real_run_*.R scripts (union of their library() calls), then writes sessionInfo()
# to supp/sessionInfo.txt. Packages that were planned but failed to build in this
# environment (and were replaced by documented open substitutes) are listed
# explicitly so the record matches Methods ("documented open substitutes").
#
# Usage:  Rscript supp/make_sessionInfo.R
.libPaths(c("F:/Rlib", .libPaths()))

# Packages actually attached by the executed pipeline (the substitutes that ran,
# not the tools that failed to build).
used <- c(
  # meta-signature / DE / curation
  "RobustRankAggreg", "data.table", "DESeq2", "limma", "GEOquery", "babelgene",
  # network / scoring / figures
  "WGCNA", "pROC", "GSVA", "ggplot2", "patchwork", "pheatmap",
  # single-cell transferability audit
  "Seurat", "Matrix", "harmony", "UCell", "CellChat",
  # Mendelian randomization
  "MendelianRandomization", "ieugwasr", "coloc",
  # enrichment / connectivity-map / annotation
  "enrichR", "signatureSearch", "ExperimentHub", "AnnotationDbi", "org.Hs.eg.db",
  "httr", "jsonlite"
)

loaded <- character(0); missing <- character(0)
for (p in used) {
  ok <- suppressWarnings(suppressMessages(
    requireNamespace(p, quietly = TRUE) &&
    require(p, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)))
  if (isTRUE(ok)) loaded <- c(loaded, p) else missing <- c(missing, p)
}

# Planned-but-unavailable packages, replaced by documented open substitutes
# (see Methods, "Where planned tools could not be built here, documented open
#  substitutes were used").
planned_substituted <- c(
  "clusterProfiler -> enrichR (GO/KEGG/Hallmark enrichment)",
  "GSVA ssGSEA      -> z-score signature score (missing binary dependency)",
  "TwoSampleMR      -> MendelianRandomization + ieugwasr",
  "STRINGdb         -> intramodular kWithin connectivity (WGCNA) for hubs"
)

con <- file("supp/sessionInfo.txt", open = "wt", encoding = "UTF-8")
writeLines(c(
  "# sessionInfo() for the dental-osteogenic-transferability pipeline.",
  "# Regenerated by supp/make_sessionInfo.R after attaching the full analysis stack",
  "# (union of all library() calls in R/step00..step11 and R/real_run_*.R).",
  paste0("# Packages successfully attached: ", length(loaded), " of ", length(used), " requested."),
  if (length(missing)) paste0("# Requested but not attachable here: ", paste(missing, collapse = ", ")) else "# All requested analysis packages attached.",
  "#",
  "# Planned tools replaced by documented open substitutes (see Methods):",
  paste0("#   - ", planned_substituted),
  "# ----------------------------------------------------------------------------",
  ""
), con)
writeLines(capture.output(sessionInfo()), con)
close(con)

cat("wrote supp/sessionInfo.txt :", length(loaded), "packages attached;",
    if (length(missing)) paste("missing:", paste(missing, collapse=",")) else "none missing", "\n")
